version: '3.8'

services:
  app:
    build: .
    container_name: pets_up_api
    command: npm run start:dev
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./project:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      DATABASE_URL: "postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres-db:5432/${POSTGRES_DB}?schema=public"
      APP_URL: "${APP_URL}"
      JWT_SECRET: "${JWT_SECRET}"
    depends_on:
      - postgres-db
  postgres-db:
    image: postgres:15-alpine
    container_name: pets_up_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - pg-data:/var/lib/postgresql/data
volumes:
  pg-data: